"""Original axonometric 3D process diagram; NOT an event/terrain simulation."""
from functools import lru_cache
import math
from PIL import Image, ImageDraw
from export_video import font
from reel_design import TEAL, GOLD, TEXT, MUTED, PANEL

SIZE = (840, 638)
SCALE = 2


def clamp(value):
    return max(0., min(1., value))


def smooth(value):
    value = clamp(value)
    return value * value * (3 - 2 * value)


def terrain_height(x, y):
    # Arbitrary relief in dimensionless units, not a DEM or geological section.
    return .075 + .86 * (max(0, 1-x/.8)**1.35) + .23 * max(0, (x-.82)/.18)**1.2 + .045*math.sin(y*6+x*4)


def project(x, y, z):
    # Entire mesh stays below phase titles and above the explanation band.
    return (135 + 540*x - 180*y, 365 + 74*x + 85*y - 200*z)


def state(progress):
    q = clamp(progress)
    slide = smooth((q-.34)/.40)
    flow = smooth((q-.74)/.26)
    phase = 0 if q < .18 else 1 if q < .34 else 2 if q < .74 else 3
    return dict(phase=phase, slide=slide, flow=flow,
                center=(.31 + .48*slide, .06 + .43*flow), scar=smooth((q-.34)/.12))


def scaled(points):
    return [(x*SCALE,y*SCALE) for x,y in points]


def surface_polygon(points):
    return [project(x,y,terrain_height(x,y)) for x,y in points]


@lru_cache(maxsize=1)
def base():
    image=Image.new('RGB',(SIZE[0]*SCALE,SIZE[1]*SCALE),PANEL)
    d=ImageDraw.Draw(image)
    def poly(points,color,outline=None):
        d.polygon(scaled(points),fill=color,outline=outline,width=2)
    # Solid block has visible front/right walls, not invented strata.
    for edge,color in [([(x,.63) for x in (0,1)],'#374844'), ([(1,y) for y in (-.63,.63)],'#293f3e')]:
        a,b=edge
        poly([project(*a,terrain_height(*a)),project(*b,terrain_height(*b)),project(*b,-.16),project(*a,-.16)],color)
    cells=[]
    for ix in range(24):
        for iy in range(18):
            x0,x1=ix/24,(ix+1)/24; y0,y1=-.63+iy*.07,-.63+(iy+1)*.07
            cells.append((y0+.45*x0,ix,iy,[(x0,y0),(x1,y0),(x1,y1),(x0,y1)]))
    for _,ix,iy,pts in sorted(cells):
        light=(((ix*17+iy*23)%13)-6)*2
        color=tuple(max(0,min(255,c+light)) for c in (63+ix//2,105+ix//3,82))
        poly(surface_polygon(pts),color)
    # Water follows the valley bottom; it is separate from the sliding mass.
    river=[]
    for i in range(46):
        y=-.63+i*1.26/45; x=.79+.014*math.sin(y*8)
        river.append(project(x,y,terrain_height(x,y)+.008))
    d.line(scaled(river),fill='#30595c',width=29*SCALE)
    d.line(scaled(river),fill=TEAL,width=13*SCALE)
    # Original stylised trees. No historical forest loss/topographic claim.
    for i in range(45):
        x=.05+((i*37)%67)/100; y=-.57+((i*47)%110)/100
        if .22<x<.44 and -.10<y<.24: continue
        px,py=project(x,y,terrain_height(x,y))
        h=12+i%7
        d.line(scaled([(px,py),(px,py-h)]),fill='#c6b28b',width=2*SCALE)
        poly([(px-8,py-h+4),(px,py-h-14),(px+8,py-h+4)],'#254c3e')
        poly([(px-6,py-h-2),(px,py-h-18),(px+6,py-h-2)],'#76a57b')
    return image


def rock(d,x,y,z,size,color):
    # Irregular closed rock/soil volumes, not flat dots or rectangular planks.
    ring=[project(x+size*dx,y+size*dy,z) for dx,dy in [(-1,-.4),(-.3,-1),(.8,-.6),(1,.3),(.1,1),(-.8,.7)]]
    peak=project(x+size*.1,y-size*.1,z+size*1.8)
    for i in range(6):
        fill=(color,'#a48966','#b49872','#897554','#9b825d',color)[i]
        d.polygon(scaled([ring[i],ring[(i+1)%6],peak]),fill=fill)


def render_piedmont(progress):
    info=state(progress); q=clamp(progress)
    image=base().copy(); d=ImageDraw.Draw(image)
    # A persistent exposed scar, never reset to an intact slope mid-scene.
    if info['scar']:
        pts=[(.23,-.07),(.31,-.105),(.40,-.055),(.433,.093),(.39,.205),(.29,.22),(.245,.137)]
        d.polygon(scaled(surface_polygon(pts)),fill='#b49773')
        for triangle,color in [([(.25,.06),(.31,-.09),(.36,.11)],'#c1a17a'),([(.36,.11),(.40,-.05),(.43,.095)],'#a58a68'),([(.28,.20),(.36,.11),(.39,.20)],'#a58d6e')]:
            d.polygon(scaled(surface_polygon(triangle)),fill=color)
    cx,cy=info['center']
    # Cohesive source parcel becomes a spread-out mixture on descent/in channel.
    blocks=[]
    for i in range(44):
        dx=(((i*37)%101)/100-.5)*(.135+.065*info['slide'])
        dy=(((i*53)%103)/102-.5)*(.21+.18*info['flow'])
        x=cx+dx*(1-.65*info['flow']); y=cy+dy
        z=terrain_height(x,y)+.016
        blocks.append((y+.45*x,x,y,z,.013+(i%4)*.003))
    for _,x,y,z,r in sorted(blocks):
        rock(d,x,y,z,r,('#c8ac81','#d4ba8f','#b59a72')[int(x*1000)%3])
    if info['phase']==0:
        # Prior wet conditions, not rainfall generated by the earthquake.
        for i in range(15):
            x=210+(i*41)%350; y=127+(i*31+q*400)%110
            d.line(scaled([(x,y),(x-5,y+13)]),fill='#83c4c4',width=2*SCALE)
    if info['phase']==1:
        # Pulse icon only: no invented shaking amplitude/time model.
        phase=(q-.18)/.16
        center=project(.45,.3,terrain_height(.45,.3))
        for offset in (0,.33,.66):
            radius=12+55*((phase+offset)%1)
            x,y=center
            d.ellipse(tuple(v*SCALE for v in (x-radius,y-radius*.3,x+radius,y+radius*.3)),outline=GOLD,width=2*SCALE)
    # Flow highlights in the actual channel, no endlessly cycling debris.
    if info['flow']>0:
        for i in range(8):
            y=.05+info['flow']*.48-i*.035
            a=project(.777,y,terrain_height(.777,y)+.027)
            b=project(.805,y+.07,terrain_height(.805,y+.07)+.027)
            d.line(scaled([a,b]),fill='#deb982',width=3*SCALE)
    image=image.resize(SIZE,Image.Resampling.LANCZOS)
    # This is a diagram phase, not a real-time clock or historical frame.
    d=ImageDraw.Draw(image)
    labels=['1 / CONDICIONES PREVIAS','2 / SACUDIDA','3 / DESLIZAMIENTO','4 / POSIBLE FLUJO EN EL CAUCE']
    d.text((30,24),'MODELO 3D PROPIO · RELIEVE CONCEPTUAL',font=font(24),fill=TEAL)
    d.text((30,66),labels[info['phase']],font=font(29),fill=GOLD)
    for xy,text in [((43,330),'Ladera'),((606,475),'Cauce')]:
        d.text(xy,text,font=font(23),fill=TEXT)
    d.text((30,546),'Agua y pendiente: condiciones del terreno.',font=font(25),fill=TEXT)
    d.text((30,582),'No recrea 1987 ni calcula velocidades o daños.',font=font(23),fill=MUTED)
    return image
