"""Evaluate detectors and a minimum-distance baseline on independent point labels.

No SCL pseudo-labels, no autogenerated labels, no pixel shared across train/test,
and no automatic winner publication. References must be spatially separated
by >=200 m between roles. Reports describe only the supplied reference sample.
"""
import argparse
from datetime import datetime
import json
from pathlib import Path
from urllib.parse import urlparse

import numpy as np
import rasterio
from rasterio.warp import transform
from fluvial_science import METHODS, CLASSES, signals, fit_minimum_distance, classify_minimum_distance, water_metrics
from build_fluvial_lab import ROOT, sha, save


def read_references(document, manifest, raw):
    if document.get("type") != "FeatureCollection" or not document.get("features"):
        raise ValueError("Independent manual references required; empty template cannot be evaluated")
    rows, ids, pixels, groups = [], set(), set(), {"train": set(), "test": set()}
    dates = {s["date"] for s in manifest["config"]["scenes"]}
    for feature in document["features"]:
        p = feature.get("properties", {}); geometry = feature.get("geometry", {})
        if geometry.get("type") != "Point" or p.get("class") not in CLASSES or p.get("role") not in groups:
            raise ValueError("Point, supported class and explicit train/test role required")
        if p.get("independent_reference") is not True or p.get("reference_type") not in ("field", "drone", "high-resolution-image"):
            raise ValueError("Independent field/drone/high-resolution labels required, not SCL or index labels")
        if p.get("date") not in dates or not isinstance(p.get("sample_id"), str) or not p["sample_id"] or p["sample_id"] in ids or not isinstance(p.get("group_id"), str) or not p["group_id"]:
            raise ValueError("Unique sample ID, spatial group and pinned acquisition date required")
        source = urlparse(p.get("evidence_uri", ""))
        if source.scheme != "https" or not source.netloc or not isinstance(p.get("observer"), str) or not p["observer"].strip():
            raise ValueError("HTTPS evidence citation and observer required")
        try:
            acquired = datetime.fromisoformat(p["reference_acquired_at"].replace("Z", "+00:00"))
            target = datetime.fromisoformat(next(s["acquired_at"] for s in manifest["regions"][0]["scenes"] if s["date"] == p["date"]).replace("Z", "+00:00"))
            if acquired.tzinfo is None: raise ValueError("Reference timestamp requires timezone")
            hours = abs((acquired - target).total_seconds()) / 3600
            if hours > 24: raise ValueError("Reference more than 24 hours from acquisition; changing rivers need contemporaneous evidence")
        except (KeyError, TypeError) as error:
            raise ValueError("Reference acquisition timestamp required") from error
        region = next((r for r in manifest["regions"] if r["id"] == p.get("region")), None)
        if region is None: raise ValueError("Known local window required")
        entry = next(s for s in region["scenes"] if s["date"] == p["date"])
        path = raw / entry["native_file"]
        if path.name != entry["native_file"] or sha(path) != entry["native_sha256"]:
            raise ValueError("Native source checksum mismatch")
        coordinates = geometry.get("coordinates", [])
        if len(coordinates) != 2 or not np.isfinite(coordinates).all() or not -180 <= coordinates[0] <= 180 or not -90 <= coordinates[1] <= 90:
            raise ValueError("Finite longitude/latitude required")
        with rasterio.open(path) as ds:
            x, y = transform("EPSG:4326", ds.crs, [coordinates[0]], [coordinates[1]])
            row, col = ds.index(x[0], y[0])
            if not 0 <= row < ds.height or not 0 <= col < ds.width:
                raise ValueError("Reference outside local window")
            v = ds.read(window=rasterio.windows.Window(col, row, 1, 1))[:, 0, 0]
            # Use projected pixel centres to detect overlaps between editorial windows.
            cx, cy = ds.xy(row, col)
        usable = bool(v[6] == 1 and np.isfinite(v[:6]).all() and np.all(v[:6] >= 0))
        pixel = (p["date"], round(cx), round(cy))
        if pixel in pixels: raise ValueError("Duplicate pixel reference (including overlapping windows)")
        pixels.add(pixel); ids.add(p["sample_id"]); groups[p["role"]].add(p["group_id"])
        rows.append({**p, "features": v[:6], "xy": (cx, cy), "usable": usable, "reference_time_gap_hours": hours})
    if groups["train"] & groups["test"]:
        raise ValueError("Spatial reference groups may not appear in both train and test")
    train = [r for r in rows if r["role"] == "train"]; test = [r for r in rows if r["role"] == "test"]
    if not train or not test or set(r["class"] for r in train) != set(CLASSES) or set(r["class"] for r in test) != set(CLASSES):
        raise ValueError("Each role needs independent examples of all four classes")
    for a in train:
        if any(np.linalg.norm(np.asarray(a["xy"]) - np.asarray(b["xy"])) < 200 for b in test):
            raise ValueError("Train/test references require >=200 m spatial separation, even on different dates")
    return rows


def evaluate(rows):
    # Do not quietly delete independent evidence where QA missed real water.
    # Classifier metrics are conditional on usable observations; coverage is
    # reported separately, including missing water references, never as dry.
    train = [r for r in rows if r["role"] == "train" and r.get("usable", True)]
    test = [r for r in rows if r["role"] == "test" and r.get("usable", True)]
    if any(set(r["class"] for r in sample) != set(CLASSES) for sample in [train, test]):
        raise ValueError("Each role needs useful independent examples of all four classes; QA omissions prevent a complete comparison")
    features = lambda sample: np.stack([r["features"] for r in sample])
    labels = lambda sample: np.array([r["class"] for r in sample])
    is_water = lambda sample: np.array([r["class"].startswith("water_") for r in sample])
    train_values = signals(features(train).T); test_values = signals(features(test).T)
    result = {}
    for method in METHODS:
        # Calibrate ONLY on training references, then freeze for held-out evaluation.
        unique = np.unique(train_values[method]); mids = (unique[:-1] + unique[1:]) / 2
        candidates = np.r_[unique[0] - 1e-5, mids, unique[-1] + 1e-5]
        best = max(candidates, key=lambda threshold: water_metrics(is_water(train), train_values[method] > threshold)["f1"] or 0)
        result[method] = {"threshold_from_train": float(best), "test": water_metrics(is_water(test), test_values[method] > best)}
    prototypes = fit_minimum_distance(features(train), labels(train))
    predictions = classify_minimum_distance(features(test), prototypes)
    matrix = np.zeros((4, 4), dtype=int)
    for actual, predicted in zip(labels(test), predictions): matrix[CLASSES.index(actual), predicted] += 1
    result["minimum_distance"] = {"test": water_metrics(is_water(test), predictions < 2), "classes": CLASSES,
                                  "confusion_matrix_actual_rows": matrix.tolist(), "prototypes_from_train": prototypes.tolist(),
                                  "status": "local-six-band-baseline-not-exact-reproduction-of-Cavallo"}
    return {"status": "evaluated-reference-sample-not-province-validation", "winner": None, "methods": result,
            "train_points": len(train), "test_points": len(test),
            "qa_coverage": {role: {label: {"references": sum(r["role"] == role and r["class"] == label for r in rows),
                                           "useful": sum(r["role"] == role and r["class"] == label and r.get("usable", True) for r in rows)}
                                    for label in CLASSES} for role in ["train", "test"]},
            "qa_missing_sample_ids": [r["sample_id"] for r in rows if not r.get("usable", True)],
            "reference_time_gap_hours_max": max(r.get("reference_time_gap_hours", 0) for r in rows),
            "limits": "Metrics conditional on useful reference pixels; QA coverage and missing reference IDs reported separately. Manual point sample, uncertain mixed pixels, spatial split. No causation, dry-duration or flow inference; no automated local winner."}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--references", type=Path, required=True, help="Independent labelled point GeoJSON")
    parser.add_argument("--raw", type=Path, default=ROOT / "data/raw/fluvial")
    parser.add_argument("--output", type=Path, default=ROOT / "data/raw/fluvial/evaluation.json")
    args = parser.parse_args()
    manifest_path = ROOT / "data/fluvial/manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    rows = read_references(json.loads(args.references.read_text(encoding="utf-8-sig")), manifest, args.raw)
    report = {**evaluate(rows), "references_sha256": sha(args.references), "manifest_sha256": sha(manifest_path), "evaluator_sha256": sha(__file__)}
    save(args.output, report)
    print("Held-out reference evaluation saved; no winner published:", args.output)
