import asyncio,json
from ux_browser import Browser,ROOT
checks=[]
async def run():
 b=await Browser().start()
 async def ev(code):return await b.evaluate("const q=id=>all().find(e=>e.id===id);"+code)
 async def version():return int(await ev("return all().find(e=>e.classList.contains('evs')).dataset.version"))
 async def click(id,commit=False):
  v=await version();await ev('q('+json.dumps(id)+').click()')
  if commit:await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2)
 async def change(id,value,commit=True):
  v=await version();await ev('const e=q('+json.dumps(id)+');e.value='+json.dumps(value)+';e.dispatchEvent(new Event("change",{bubbles:true}))')
  if commit:await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2)
 async def check(expression,label):
  value=await ev('return '+expression)
  if not value:raise AssertionError(label)
  checks.append(label)
  print('PASS',label,flush=True)
 async def rect(selector):return await ev('const r=all().find(e=>e.matches('+json.dumps(selector)+')).getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}')
 async def drag(selector,dx,dy):
  v=await version();r=await rect(selector);x=r['x']+r['w']/2;y=r['y']+r['h']/2
  await b.call('Input.dispatchMouseEvent',{'type':'mouseMoved','x':x,'y':y})
  await b.call('Input.dispatchMouseEvent',{'type':'mousePressed','x':x,'y':y,'button':'left','clickCount':1})
  await b.call('Input.dispatchMouseEvent',{'type':'mouseMoved','x':x+dx,'y':y+dy,'button':'left','buttons':1})
  await b.call('Input.dispatchMouseEvent',{'type':'mouseReleased','x':x+dx,'y':y+dy,'button':'left','clickCount':1})
  await b.shot('debug-drag.png')
  print('DRAG',await ev("return {x:q('x').value,y:q('y').value,pending:q('pending').textContent,version:all().find(e=>e.classList.contains('evs')).dataset.version,errors:all().filter(e=>e.id==='workspace-status').map(e=>e.textContent)}"),flush=True)
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2)
 try:
  await b.call('Runtime.enable');await b.call('Page.navigate',{'url':'http://127.0.0.1:8512'})
  await b.wait("all().some(e=>e.tagName==='BUTTON'&&e.textContent.includes('5 · Estudio'))")
  await b.evaluate("all().find(e=>e.tagName==='BUTTON'&&e.textContent.includes('5 · Estudio')).click()")
  await b.wait("all().some(e=>e.id==='scene-duration')");await b.size(1366,768)
  await change('project-name','UX · verificación Chrome')
  await click('project-menu');await ev("[...q('dialog-body').querySelectorAll('button')].find(e=>e.textContent.includes('Nuevo proyecto')).click()")
  await b.wait("all().some(e=>e.id==='scene-label'&&e.textContent==='Lienzo vacío')")
  await check("q('layers').children.length===0",'blank scene')
  await click('format');await ev("q('dialog-body').querySelector('select').value='custom';q('dialog-body').querySelector('select').dispatchEvent(new Event('change'))")
  await ev("const inputs=q('dialog-body').querySelectorAll('input');inputs[0].value=640;inputs[1].value=360;[...q('dialog-body').querySelectorAll('button')].find(e=>e.textContent.includes('Adaptar')).click()")
  await b.wait("all().some(e=>e.id==='resolution'&&e.textContent.includes('640 × 360'))")
  await click('addtext',True)
  await ev("q('layers').querySelector('button').click()")
  await check("q('inspector-title').textContent==='Texto'",'contextual text selection')
  v=await version();await ev("q('text').value='Ciencia en movimiento';q('text').dispatchEvent(new Event('input',{bubbles:true}))")
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2)
  await check("q('text').value==='Ciencia en movimiento'",'text autosave and renderer rerun')
  await change('font-family','Atkinson Hyperlegible')
  await check("q('font-family').value==='Atkinson Hyperlegible'",'font persistence')
  before=float(await ev("return q('x').value"));await drag('.piece',25,15)
  await check("Number(q('x').value)>"+str(before),'real mouse drag committed')
  width=float(await ev("return q('w').value"));await drag('.handle',30,20)
  await check("Number(q('w').value)>"+str(width),'real resize committed')
  v=await version();await ev("all().find(e=>e.classList.contains('stage')).focus()")
  await b.call('Input.dispatchKeyEvent',{'type':'keyDown','key':'ArrowRight','code':'ArrowRight','windowsVirtualKeyCode':39})
  await b.call('Input.dispatchKeyEvent',{'type':'keyUp','key':'ArrowRight','code':'ArrowRight','windowsVirtualKeyCode':39})
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));checks.append('keyboard move autosaved')
  await click('undo',True);await click('redo',True);checks.append('document undo redo')
  await click('addshape',True)
  await ev("const rows=q('layers').querySelectorAll('.layer-row');rows[0].querySelector('button').click();rows[1].querySelector('button').dispatchEvent(new MouseEvent('click',{shiftKey:true,bubbles:true}))")
  await check("q('inspector-title').textContent.includes('2 elementos')",'multiple selection')
  await click('group',True);await check("q('layers').querySelectorAll('.group-heading').length===1",'persistent group hierarchy')
  await drag('.piece',-12,12);checks.append('group move')
  await click('ungroup',True);await check("!q('layers').querySelector('.group-heading')",'ungroup persisted')
  await ev("q('layers').lastElementChild.querySelector('button').click()")
  await click('layerup',True);checks.append('layer ordering')
  v=await version();await ev("q('layers').querySelectorAll('.layer-row')[0].querySelectorAll('button')[2].click()")
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2)
  await check("q('locked').checked&&q('x').disabled",'lock guards inspector')
  await ev("q('locked').checked=false;q('locked').dispatchEvent(new Event('change',{bubbles:true}))")
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v+1));await asyncio.sleep(.2)
  await ev("q('layers').querySelectorAll('.layer-row')[0].querySelectorAll('button')[1].click()")
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v+2));checks.append('visibility autosaved')
  await ev("all().find(e=>e.dataset.tab==='templates').click()")
  await check("q('library-content').querySelectorAll('.resource-card').length===11",'eleven templates exposed')
  await ev("[...q('library-content').querySelectorAll('button')].find(e=>e.textContent.includes('Portada')).click()")
  await b.wait("all().some(e=>e.id==='scene-label'&&e.textContent==='Portada')");checks.append('template adds real scene')
  await change('scene-duration',.4)
  await click('scene-duplicate',True);await check("q('scenes').children.length===3",'scene duplication')
  v=await version();await ev("q('scenes').lastElementChild.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',shiftKey:true,bubbles:true}))")
  await b.wait("Number(all().find(e=>e.classList.contains('evs')).dataset.version)>"+str(v));await asyncio.sleep(.2);checks.append('timeline keyboard reorder')
  await change('playhead',1,False);await b.wait("all().some(e=>e.id==='canvas-mode'&&e.textContent.includes('CUADRO'))");checks.append('timeline seek exact frame')
  await click('back-edit');await b.shot('after-interactions-1366.png')
  print(json.dumps({'checks':checks,'count':len(checks)}));(ROOT/'ux-redesign'/'interactions.json').write_text(json.dumps(checks,indent=2))
  errors=[e for e in b.events if e.get('method')=='Runtime.exceptionThrown'];assert not errors,errors
 except Exception:
  await b.shot('debug-failure.png');print('FAILED_STATE',await ev("return {inspector:q('inspector-title')?.textContent,status:q('workspace-status')?.textContent,save:q('save-state')?.textContent,pending:q('pending')?.textContent}"),flush=True);raise
 finally:await b.close()
asyncio.run(run())
